packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - bufferutil
  - keccak
  - sharp
  - unrs-resolver
  - utf-8-validate
allowBuilds:
  bufferutil: true
  keccak: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
