export type BnbxAiLanguage = "zh" | "en" | "ko" | "ja";

const refusalCopy: Record<BnbxAiLanguage, string> = {
  zh: "抱歉，小壹仅提供 BNBX 平台、代币发行、交易机制、合约风险与钱包安全相关服务，无法回答涉及政治、政治人物或宗教的问题。",
  en: "Sorry, X-One only assists with BNBX, token launches, trading mechanics, contract risks, and wallet safety. I can’t answer questions involving politics, political figures, or religion.",
  ko: "죄송합니다. X-One은 BNBX, 토큰 출시, 거래 방식, 컨트랙트 위험 및 지갑 보안만 안내하며 정치, 정치인 또는 종교 관련 질문에는 답변할 수 없습니다.",
  ja: "申し訳ありません。X-OneはBNBX、トークン発行、取引の仕組み、コントラクトリスク、ウォレット安全のみをご案内しており、政治・政治家・宗教に関する質問には回答できません。",
};

const sensitiveTerms = [
  // Broad political and religious topics.
  "politic",
  "government",
  "president",
  "prime minister",
  "election",
  "parliament",
  "congress",
  "senate",
  "communis",
  "socialis",
  "fascis",
  "democra",
  "republican party",
  "democratic party",
  "conservative party",
  "labour party",
  "religion",
  "religious",
  "christian",
  "catholic",
  "protestant",
  "islam",
  "muslim",
  "judaism",
  "jewish",
  "hindu",
  "buddh",
  "taoism",
  "shinto",
  "church",
  "mosque",
  "temple",
  "bible",
  "quran",
  "torah",
  "pope",
  "rabbi",
  "priest",
  "pastor",
  "prophet",
  "jesus",
  "christ",
  "muhammad",
  "allah",
  "buddha",
  // Political figures and common aliases.
  "donald trump",
  "trump",
  "joe biden",
  "biden",
  "barack obama",
  "kamala harris",
  "xi jinping",
  "vladimir putin",
  "putin",
  "volodymyr zelensky",
  "zelensky",
  "narendra modi",
  "benjamin netanyahu",
  "kim jong un",
  "emmanuel macron",
  "recep tayyip erdogan",
  "mao zedong",
  "stalin",
  "hitler",
  // Simplified Chinese.
  "政治",
  "政党",
  "政府",
  "国家领导人",
  "总统",
  "首相",
  "总理",
  "主席",
  "议会",
  "国会",
  "选举",
  "投票",
  "民主党",
  "共和党",
  "共产党",
  "国民党",
  "意识形态",
  "共产主义",
  "社会主义",
  "法西斯",
  "宗教",
  "信仰",
  "基督教",
  "天主教",
  "伊斯兰教",
  "穆斯林",
  "犹太教",
  "佛教",
  "道教",
  "印度教",
  "圣经",
  "古兰经",
  "教会",
  "教堂",
  "清真寺",
  "寺庙",
  "上帝",
  "真主",
  "耶稣",
  "穆罕默德",
  "释迦牟尼",
  "佛祖",
  "教皇",
  "特朗普",
  "川普",
  "拜登",
  "奥巴马",
  "哈里斯",
  "习近平",
  "普京",
  "泽连斯基",
  "莫迪",
  "内塔尼亚胡",
  "金正恩",
  "马克龙",
  "埃尔多安",
  "毛泽东",
  "斯大林",
  "希特勒",
  // Platform-specific blocked names.
  "王子文",
  // Korean and Japanese topic words.
  "정치",
  "정부",
  "대통령",
  "총리",
  "선거",
  "국회",
  "정당",
  "종교",
  "기독교",
  "이슬람",
  "불교",
  "성경",
  "政治",
  "政府",
  "大統領",
  "首相",
  "選挙",
  "国会",
  "政党",
  "宗教",
  "キリスト教",
  "イスラム教",
  "仏教",
] as const;

function normalize(input: string) {
  return input.normalize("NFKC").toLocaleLowerCase();
}

export function involvesPoliticsOrReligion(input: string) {
  const normalized = normalize(input);
  const compact = normalized.replace(/[\s._·•—–\-/\\|]+/g, "");
  return sensitiveTerms.some((term) => {
    const normalizedTerm = normalize(term);
    return (
      normalized.includes(normalizedTerm) ||
      compact.includes(normalizedTerm.replace(/\s+/g, ""))
    );
  });
}

export function sensitiveTopicRefusal(language: BnbxAiLanguage) {
  return refusalCopy[language] ?? refusalCopy.en;
}
