"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "zh" | "en" | "ko" | "ja";
export type Theme = "dark" | "light";

const messages: Record<Language, Record<string, string>> = {
  zh: {
    market: "市场", create: "创建代币", today: "今日毕业", history: "历史毕业",
    projects: "实时项目", hot: "热门", latest: "最新", graduating: "即将打满", graduated: "历史毕业",
    buy: "买入", sell: "卖出", buyWith: "使用 BNB 买入", sellToken: "卖出代币",
    expectedGet: "预计获得", expectedReceive: "预计收到", fee: "交易手续费",
    switchNetwork: "切换到 BNB 主网", firstApproveSell: "首次授权并卖出",
    approving: "等待授权确认…", selling: "等待卖出确认…", balance: "余额",
    progress: "毕业进度", target: "目标", loading: "读取中…", internal: "内盘",
    graduatingState: "毕业中", graduatedState: "已毕业", noMatch: "暂无符合条件的项目",
    risk: "数字资产具有高度风险。请独立研究并谨慎交易。",
    deploy: "部署代币", browse: "浏览内盘", copied: "已复制 ✓", copy: "复制",
    recentTrades: "最近交易", holders: "持币地址", topTraders: "活跃交易者", noTopTraders: "暂无可识别的活跃交易者。", top10Concentration: "前十大地址持仓占比", noTrades: "还没有链上交易。", noHolders: "暂无持币地址。",
    readingLogs: "正在读取链上数据…", items: "条", addresses: "个", theme: "切换黑白模式",
    connectWallet: "连接钱包", connectingWallet: "连接中…", openInWallet: "在钱包中打开",
    createTitle: "配置代币", tokenName: "代币名称", tokenSymbol: "代币符号", tokenIntro: "代币简介（选填）",
    tokenLogo: "代币 Logo（选填）", socialLinks: "社区链接（选填）", graduationTarget: "毕业额度",
    creatorBuy: "创建者首购（选填）", createToken: "创建代币",
    curveTrading: "内盘交易", preparing: "准备毕业", pancake: "PancakeSwap V2",
    myBalance: "我的余额", supply: "固定总供应量", factoryPermission: "Factory 配置权限",
    graduationPermission: "毕业解锁权限", pairStatus: "Pair 转账状态", abandoned: "已放弃",
    destroyed: "已销毁", curveOnly: "仅自动曲线", protected: "毕业前保护中", unlocked: "毕业后已开放",
    confirmed: "交易已确认。", txHash: "交易哈希",
    searchPlaceholder: "输入代币名称、符号或合约地址",
    qqGroupNumber: "QQ群", qqGroupCopied: "QQ群信息已复制，请打开QQ搜索加入",
    websitePlaceholder: "请填写你的官方网站链接 / 可不填写",
    telegramPlaceholder: "请填写你的 Telegram 社区链接 / 可不填写",
    twitterPlaceholder: "请填写你的 X（Twitter）链接 / 可不填写",
    deboxPlaceholder: "请填写你的 DeBox 社区链接 / 可不填写",
    qqPlaceholder: "请填写你的社区的QQ群 / 可不填写",
    totalProjects: "项目总数", activeProjects: "内盘交易", nearGraduation: "即将打满", completedProjects: "已毕业",
    chainBusy: "链上节点暂时繁忙，正在自动切换备用 RPC…", holderSyncBusy: "持币数据同步延迟，将在下一轮自动重试。",
    direction: "方向", account: "账户", tokenAmount: "代币", date: "日期", units: "枚",
    chartSyncing: "正在同步链上成交…", chartEmpty: "暂无成交，首笔买入后生成第一根 K 线。",
    chartBusy: "RPC 日志读取繁忙，K 线将在下一轮自动重试。", priceUnit: "价格单位：BNB / 100万枚代币",
    volume: "成交量", liveRefresh: "链上实时 · 15秒刷新", chartTruth: "K 线只使用 BNB Chain Mainnet 上真实的内盘买卖事件，不生成模拟数据。",
    templateSelect: "选择代币模板", available: "已开放", unavailable: "暂未开放",
    namePlaceholder: "例如 BNBX Cat", symbolPlaceholder: "例如 BCAT 或 bcat",
    descriptionPlaceholder: "介绍代币、社区和 Meme 故事（最多 500 字）", logoHelp: "支持 JPG、PNG、WebP、GIF，最大 2MB。",
    initialBuyPlaceholder: "输入 BNB 金额", decreaseTarget: "减少 0.01 BNB", increaseTarget: "增加 0.01 BNB",
    factoryMissing: "主网 Factory 合约地址尚未配置。完成部署和验证后，创建按钮将自动解锁。",
    uploading: "正在上传到 IPFS…", preparingAddress: "正在准备 1111 尾号合约地址…", walletConfirm: "请在钱包确认…",
    submitted: "交易已广播", confirming: "链上确认中", syncing: "数据同步中", completed: "已完成",
    creationSuccess: "代币已成功创建在 BNB 主网。", creationFailed: "链上执行失败。请勿重复提交，并保存交易哈希以便诊断。",
    safetyTitle: "链上安全信息", verifiedFactory: "官方 Factory", verified: "可验证", tokenTax: "代币税", zeroTax: "永久 0%", slippage: "报价保护", fixedFee: "内盘手续费",
    txStatus: "交易状态", walletStep: "钱包确认", broadcastStep: "已发送", confirmStep: "链上确认", syncStep: "刷新数据",
    chooseWallet: "选择钱包", walletConnectHelp: "选择已安装的钱包连接 BNB Chain", walletAccount: "我的钱包",
    copyAddress: "复制钱包地址", viewExplorer: "在 BscScan 查看", disconnectWallet: "断开连接",
    installed: "已安装", install: "安装 / 打开", close: "关闭", walletSafety: "BNBX 不会要求你的助记词或私钥。",
    chooseNetwork: "选择区块链", currentNetwork: "当前网络", comingSoon: "即将支持",
    networkRoadmap: "BNBX 多链发射路线", networkSoonHelp: "目前仅 BNB Chain 可用，其他链将在完成合约部署与安全验收后开放。",
    raisedBnb: "当前已募集", remainingBnb: "距离打满还需", curveRemaining: "内盘剩余代币",
    automaticMigration: "打满后自动迁移至 PancakeSwap V2，LP 永久销毁。",
    token: "代币", creator: "创建者", creatorProjects: "创建者项目记录", launchTime: "创建时间", currentPrice: "当前价格", change24h: "24h 涨跌", liquidity: "流动性", marketCap: "估算市值",
    onchainVolume: "链上成交量", volume24h: "24h 成交量", trades24h: "24h 交易", marketData: "市场数据", officialSite: "官网",
    tokenDescription: "代币介绍", noTokenDescription: "创建者暂未填写代币介绍。",
    expandDescription: "展开全文", collapseDescription: "收起", securityDetails: "查看完整安全信息",
    hideSecurityDetails: "收起安全信息", mobileMenu: "打开菜单", language: "语言",
    moreLinks: "更多", hideLinks: "收起", retry: "重新读取",
    dataUnknown: "数据待确认", dataUnavailable: "链上数据暂时无法读取",
    dataUnavailableHelp: "没有把读取失败显示成 0；请稍后重试，交易前以 BscScan 为准。",
    partialDataNotice: "部分链上字段暂未返回，未知数据已显示为“—”，不会伪装成 0。",
    staleDataNotice: "实时更新暂时失败，当前保留上一次成功数据。",
    noProjectsYet: "暂时没有已发布项目", noProjectsHelp: "Factory 读取正常，但目前没有可展示的代币。",
    metadataUnavailable: "代币资料暂时无法读取，不能据此判断创建者未填写介绍。",
    transactionPreview: "钱包交易预览", destination: "交互合约",
    creationFee: "部署费", initialBuyValue: "创建者首购", totalSend: "钱包发送总额",
    minimumReceive: "最低收到", slippageProtected: "1% 最低收币保护",
    tradeLine: "逐笔成交", lastUpdated: "更新",
    securityCenter: "安全与合约", discussion: "项目讨论", signatureNoGas: "钱包签名 · 不消耗 Gas", commentPlaceholder: "分享项目观点或最新动态（最多 280 字）", connectToComment: "连接钱包后参与讨论", postComment: "签名并发布", noComments: "还没有评论，成为第一个参与讨论的人。", commentsUnavailable: "评论服务暂时不可用，请稍后重试。", commentFailed: "评论发布失败。",
  },
  en: {
    market: "Market", create: "Create Token", today: "Graduating", history: "Graduated",
    projects: "Live Projects", hot: "Hot", latest: "Latest", graduating: "Graduating", graduated: "Graduated",
    buy: "Buy", sell: "Sell", buyWith: "Buy with BNB", sellToken: "Sell Token",
    expectedGet: "You receive", expectedReceive: "You receive", fee: "Trading fee",
    switchNetwork: "Switch to BNB Mainnet", firstApproveSell: "Approve once & sell",
    approving: "Confirming approval…", selling: "Confirming sale…", balance: "Balance",
    progress: "Graduation progress", target: "Target", loading: "Loading…", internal: "Bonding Curve",
    graduatingState: "Migrating", graduatedState: "Graduated", noMatch: "No matching projects",
    risk: "Digital assets are highly risky. Do your own research and trade carefully.",
    deploy: "Create Token", browse: "Explore Market", copied: "Copied ✓", copy: "Copy",
    recentTrades: "Recent Trades", holders: "Holders", topTraders: "Top Traders", noTopTraders: "No identifiable active traders yet.", top10Concentration: "Top 10 holder concentration", noTrades: "No on-chain trades yet.", noHolders: "No holders yet.",
    readingLogs: "Loading on-chain data…", items: "trades", addresses: "holders", theme: "Toggle light or dark mode",
    connectWallet: "Connect Wallet", connectingWallet: "Connecting…", openInWallet: "Open in Wallet",
    createTitle: "Configure Token", tokenName: "Token Name", tokenSymbol: "Token Symbol", tokenIntro: "Description (Optional)",
    tokenLogo: "Token Logo (Optional)", socialLinks: "Community Links (Optional)", graduationTarget: "Graduation Target",
    creatorBuy: "Creator Initial Buy (Optional)", createToken: "Create Token",
    curveTrading: "Bonding Curve", preparing: "Preparing Graduation", pancake: "PancakeSwap V2",
    myBalance: "My balance", supply: "Fixed total supply", factoryPermission: "Factory permissions",
    graduationPermission: "Graduation authority", pairStatus: "Pair transfer status", abandoned: "Renounced",
    destroyed: "Burned", curveOnly: "Automatic curve only", protected: "Protected before graduation", unlocked: "Unlocked after graduation",
    confirmed: "Transaction confirmed.", txHash: "Transaction hash",
    searchPlaceholder: "Search by token name, symbol, or contract",
    qqGroupNumber: "QQ Group", qqGroupCopied: "QQ group information copied. Search for it in QQ to join.",
    websitePlaceholder: "Enter your official website / Optional",
    telegramPlaceholder: "Enter your Telegram community / Optional",
    twitterPlaceholder: "Enter your X (Twitter) link / Optional",
    deboxPlaceholder: "Enter your DeBox community / Optional",
    qqPlaceholder: "Enter your community QQ group / Optional",
    totalProjects: "Total projects", activeProjects: "Bonding curve", nearGraduation: "Near graduation", completedProjects: "Graduated",
    chainBusy: "The chain node is busy. Switching to a backup RPC automatically…", holderSyncBusy: "Holder data is delayed and will retry automatically.",
    direction: "Side", account: "Account", tokenAmount: "Token", date: "Date", units: "tokens",
    chartSyncing: "Syncing on-chain trades…", chartEmpty: "No trades yet. The first buy will create the first candle.",
    chartBusy: "RPC logs are busy. The chart will retry automatically.", priceUnit: "Price: BNB per 1M tokens",
    volume: "Volume", liveRefresh: "On-chain live · 15s refresh", chartTruth: "Candles use real BNB Chain Mainnet bonding-curve trades only. No simulated data.",
    templateSelect: "Choose a token template", available: "AVAILABLE", unavailable: "NOT AVAILABLE",
    namePlaceholder: "e.g. BNBX Cat", symbolPlaceholder: "e.g. BCAT or bcat",
    descriptionPlaceholder: "Describe the token, community, and meme story (500 characters max)", logoHelp: "JPG, PNG, WebP, or GIF. 2MB maximum.",
    initialBuyPlaceholder: "Enter BNB amount", decreaseTarget: "Decrease by 0.01 BNB", increaseTarget: "Increase by 0.01 BNB",
    factoryMissing: "The mainnet Factory is not configured. Creation unlocks after deployment and verification.",
    uploading: "Uploading to IPFS…", preparingAddress: "Preparing a contract address ending in 1111…", walletConfirm: "Confirm in wallet…",
    submitted: "Transaction broadcast", confirming: "Confirming on-chain", syncing: "Syncing data", completed: "Completed",
    creationSuccess: "Token successfully created on BNB Mainnet.", creationFailed: "On-chain execution failed. Do not resubmit; save the transaction hash for diagnosis.",
    safetyTitle: "On-chain safety", verifiedFactory: "Official Factory", verified: "Verifiable", tokenTax: "Token tax", zeroTax: "Permanent 0%", slippage: "Quote protection", fixedFee: "Curve fee",
    txStatus: "Transaction status", walletStep: "Wallet approval", broadcastStep: "Broadcast", confirmStep: "On-chain confirmation", syncStep: "Data refresh",
    chooseWallet: "Choose a wallet", walletConnectHelp: "Connect an installed wallet to BNB Chain", walletAccount: "My wallet",
    copyAddress: "Copy wallet address", viewExplorer: "View on BscScan", disconnectWallet: "Disconnect",
    installed: "Installed", install: "Install / Open", close: "Close", walletSafety: "BNBX will never ask for your recovery phrase or private key.",
    chooseNetwork: "Select blockchain", currentNetwork: "Current", comingSoon: "Coming soon",
    networkRoadmap: "BNBX multichain roadmap", networkSoonHelp: "Only BNB Chain is live. Other chains unlock after contract deployment and security verification.",
    raisedBnb: "BNB raised", remainingBnb: "BNB to graduation", curveRemaining: "Tokens remaining",
    automaticMigration: "At 100%, liquidity migrates to PancakeSwap V2 and LP is burned permanently.",
    token: "Token", creator: "Creator", creatorProjects: "Creator launch history", launchTime: "Created", currentPrice: "Current price", change24h: "24h change", liquidity: "Liquidity", marketCap: "Estimated market cap",
    onchainVolume: "On-chain volume", volume24h: "24h volume", trades24h: "24h trades", marketData: "Market data", officialSite: "Website",
    tokenDescription: "Token description", noTokenDescription: "The creator has not added a token description.",
    expandDescription: "Read more", collapseDescription: "Show less", securityDetails: "View full safety details",
    hideSecurityDetails: "Hide safety details", mobileMenu: "Open menu", language: "Language",
    moreLinks: "More", hideLinks: "Show less", retry: "Retry",
    dataUnknown: "Pending verification", dataUnavailable: "On-chain data is temporarily unavailable",
    dataUnavailableHelp: "Failed reads are not shown as zero. Retry shortly and verify on BscScan before trading.",
    partialDataNotice: "Some fields are delayed. Unknown values are shown as “—”, never as a fake zero.",
    staleDataNotice: "Live refresh failed temporarily. The last successful data is still displayed.",
    noProjectsYet: "No published projects yet", noProjectsHelp: "Factory data loaded successfully, but there are no tokens to display.",
    metadataUnavailable: "Token metadata is temporarily unavailable; this does not mean the creator left it blank.",
    transactionPreview: "Wallet transaction preview", destination: "Contract",
    creationFee: "Creation fee", initialBuyValue: "Creator initial buy", totalSend: "Total wallet value",
    minimumReceive: "Minimum received", slippageProtected: "1% minimum-output protection",
    tradeLine: "Trade line", lastUpdated: "Updated",
    securityCenter: "Safety & Contracts", discussion: "Project Discussion", signatureNoGas: "Wallet signature · no gas", commentPlaceholder: "Share research or a project update (280 characters)", connectToComment: "Connect your wallet to join the discussion", postComment: "Sign & post", noComments: "No comments yet. Start the discussion.", commentsUnavailable: "Comments are temporarily unavailable.", commentFailed: "Comment could not be posted.",
  },
  ko: {
    market: "마켓", create: "토큰 생성", today: "졸업 예정", history: "졸업 기록",
    projects: "실시간 프로젝트", hot: "인기", latest: "최신", graduating: "졸업 예정", graduated: "졸업 완료",
    buy: "구매", sell: "판매", buyWith: "BNB로 구매", sellToken: "토큰 판매",
    expectedGet: "예상 수령", expectedReceive: "예상 수령", fee: "거래 수수료",
    switchNetwork: "BNB 메인넷으로 전환", firstApproveSell: "최초 승인 후 판매",
    approving: "승인 확인 중…", selling: "판매 확인 중…", balance: "잔액",
    progress: "졸업 진행률", target: "목표", loading: "불러오는 중…", internal: "본딩 커브",
    graduatingState: "졸업 중", graduatedState: "졸업 완료", noMatch: "조건에 맞는 프로젝트가 없습니다",
    risk: "디지털 자산은 고위험 상품입니다. 직접 조사하고 신중히 거래하세요.",
    deploy: "토큰 생성", browse: "마켓 보기", copied: "복사됨 ✓", copy: "복사",
    recentTrades: "최근 거래", holders: "홀더", topTraders: "활성 트레이더", noTopTraders: "식별 가능한 활성 트레이더가 없습니다.", top10Concentration: "상위 10개 주소 보유 비중", noTrades: "아직 온체인 거래가 없습니다.", noHolders: "아직 홀더가 없습니다.",
    readingLogs: "온체인 데이터 불러오는 중…", items: "건", addresses: "명", theme: "라이트/다크 모드 전환",
    connectWallet: "지갑 연결", connectingWallet: "연결 중…", openInWallet: "지갑에서 열기",
    createTitle: "토큰 설정", tokenName: "토큰 이름", tokenSymbol: "토큰 심볼", tokenIntro: "토큰 소개 (선택)",
    tokenLogo: "토큰 로고 (선택)", socialLinks: "커뮤니티 링크 (선택)", graduationTarget: "졸업 목표",
    creatorBuy: "생성자 최초 구매 (선택)", createToken: "토큰 생성",
    curveTrading: "본딩 커브", preparing: "졸업 준비", pancake: "PancakeSwap V2",
    myBalance: "내 잔액", supply: "고정 총 공급량", factoryPermission: "Factory 권한",
    graduationPermission: "졸업 권한", pairStatus: "Pair 전송 상태", abandoned: "권한 포기",
    destroyed: "소각됨", curveOnly: "자동 커브 전용", protected: "졸업 전 보호", unlocked: "졸업 후 개방",
    confirmed: "거래가 확인되었습니다.", txHash: "거래 해시",
    searchPlaceholder: "토큰 이름, 심볼 또는 컨트랙트 검색",
    qqGroupNumber: "QQ 그룹", qqGroupCopied: "QQ 그룹 정보가 복사되었습니다. QQ에서 검색하여 가입하세요。",
    websitePlaceholder: "공식 웹사이트를 입력하세요 / 선택",
    telegramPlaceholder: "Telegram 커뮤니티를 입력하세요 / 선택",
    twitterPlaceholder: "X (Twitter) 링크를 입력하세요 / 선택",
    deboxPlaceholder: "DeBox 커뮤니티를 입력하세요 / 선택",
    qqPlaceholder: "커뮤니티 QQ 그룹을 입력하세요 / 선택",
    totalProjects: "전체 프로젝트", activeProjects: "본딩 커브", nearGraduation: "졸업 임박", completedProjects: "졸업 완료",
    chainBusy: "체인 노드가 혼잡합니다. 백업 RPC로 자동 전환 중입니다…", holderSyncBusy: "홀더 데이터가 지연되어 자동으로 다시 시도합니다.",
    direction: "구분", account: "계정", tokenAmount: "토큰", date: "날짜", units: "개",
    chartSyncing: "온체인 거래 동기화 중…", chartEmpty: "아직 거래가 없습니다. 첫 구매 후 첫 캔들이 생성됩니다.",
    chartBusy: "RPC 로그가 혼잡합니다. 차트가 자동으로 다시 시도합니다.", priceUnit: "가격: BNB / 토큰 100만 개",
    volume: "거래량", liveRefresh: "온체인 실시간 · 15초 갱신", chartTruth: "실제 BNB Chain Mainnet 본딩 커브 거래만 사용하며 모의 데이터는 생성하지 않습니다.",
    templateSelect: "토큰 템플릿 선택", available: "사용 가능", unavailable: "사용 불가",
    namePlaceholder: "예: BNBX Cat", symbolPlaceholder: "예: BCAT 또는 bcat",
    descriptionPlaceholder: "토큰, 커뮤니티와 밈 스토리를 소개하세요 (최대 500자)", logoHelp: "JPG, PNG, WebP, GIF 지원, 최대 2MB.",
    initialBuyPlaceholder: "BNB 금액 입력", decreaseTarget: "0.01 BNB 감소", increaseTarget: "0.01 BNB 증가",
    factoryMissing: "메인넷 Factory가 설정되지 않았습니다. 배포와 검증 후 생성 기능이 열립니다.",
    uploading: "IPFS에 업로드 중…", preparingAddress: "1111로 끝나는 컨트랙트 주소 준비 중…", walletConfirm: "지갑에서 확인하세요…",
    submitted: "거래 전송 완료", confirming: "온체인 확인 중", syncing: "데이터 동기화 중", completed: "완료",
    creationSuccess: "BNB Mainnet에 토큰을 생성했습니다.", creationFailed: "온체인 실행에 실패했습니다. 다시 제출하지 말고 진단을 위해 거래 해시를 보관하세요.",
    safetyTitle: "온체인 보안 정보", verifiedFactory: "공식 Factory", verified: "검증 가능", tokenTax: "토큰 세금", zeroTax: "영구 0%", slippage: "호가 보호", fixedFee: "본딩 커브 수수료",
    txStatus: "거래 상태", walletStep: "지갑 확인", broadcastStep: "전송됨", confirmStep: "온체인 확인", syncStep: "데이터 갱신",
    chooseWallet: "지갑 선택", walletConnectHelp: "설치된 지갑으로 BNB Chain에 연결하세요", walletAccount: "내 지갑",
    copyAddress: "지갑 주소 복사", viewExplorer: "BscScan에서 보기", disconnectWallet: "연결 해제",
    installed: "설치됨", install: "설치 / 열기", close: "닫기", walletSafety: "BNBX는 복구 문구나 개인 키를 요구하지 않습니다.",
    chooseNetwork: "블록체인 선택", currentNetwork: "현재 네트워크", comingSoon: "출시 예정",
    networkRoadmap: "BNBX 멀티체인 로드맵", networkSoonHelp: "현재 BNB Chain만 사용할 수 있습니다. 다른 체인은 컨트랙트 배포와 보안 검증 후 지원됩니다.",
    raisedBnb: "현재 모금액", remainingBnb: "졸업까지 남은 BNB", curveRemaining: "본딩 커브 잔여 토큰",
    automaticMigration: "100% 달성 시 PancakeSwap V2로 자동 이전되고 LP는 영구 소각됩니다.",
    token: "토큰", creator: "생성자", creatorProjects: "생성자 프로젝트 기록", launchTime: "생성일", currentPrice: "현재 가격", change24h: "24시간 변동", liquidity: "유동성", marketCap: "추정 시가총액",
    onchainVolume: "온체인 거래량", volume24h: "24시간 거래량", trades24h: "24시간 거래", marketData: "시장 데이터", officialSite: "웹사이트",
    tokenDescription: "토큰 소개", noTokenDescription: "생성자가 토큰 소개를 입력하지 않았습니다.",
    expandDescription: "전체 보기", collapseDescription: "접기", securityDetails: "전체 보안 정보 보기",
    hideSecurityDetails: "보안 정보 접기", mobileMenu: "메뉴 열기", language: "언어",
    moreLinks: "더보기", hideLinks: "접기", retry: "다시 불러오기",
    dataUnknown: "확인 대기", dataUnavailable: "온체인 데이터를 일시적으로 불러올 수 없습니다",
    dataUnavailableHelp: "읽기 실패를 0으로 표시하지 않습니다. 잠시 후 다시 시도하고 거래 전 BscScan에서 확인하세요.",
    partialDataNotice: "일부 필드가 지연되고 있습니다. 알 수 없는 값은 가짜 0이 아닌 “—”로 표시됩니다.",
    staleDataNotice: "실시간 갱신이 일시적으로 실패해 마지막 정상 데이터를 표시합니다.",
    noProjectsYet: "아직 공개된 프로젝트가 없습니다", noProjectsHelp: "Factory 데이터는 정상적으로 불러왔지만 표시할 토큰이 없습니다.",
    metadataUnavailable: "토큰 메타데이터를 일시적으로 불러올 수 없습니다. 생성자가 입력하지 않았다는 뜻은 아닙니다.",
    transactionPreview: "지갑 거래 미리보기", destination: "상호작용 컨트랙트",
    creationFee: "생성 수수료", initialBuyValue: "생성자 최초 구매", totalSend: "지갑 전송 총액",
    minimumReceive: "최소 수령량", slippageProtected: "1% 최소 수령 보호",
    tradeLine: "체결 추이", lastUpdated: "업데이트",
    securityCenter: "보안 및 컨트랙트", discussion: "프로젝트 토론", signatureNoGas: "지갑 서명 · 가스 없음", commentPlaceholder: "프로젝트 의견이나 소식을 공유하세요 (최대 280자)", connectToComment: "지갑을 연결해 토론에 참여하세요", postComment: "서명 후 게시", noComments: "아직 댓글이 없습니다.", commentsUnavailable: "댓글 서비스를 일시적으로 사용할 수 없습니다.", commentFailed: "댓글 게시에 실패했습니다.",
  },
  ja: {
    market: "マーケット", create: "トークン作成", today: "卒業予定", history: "卒業履歴",
    projects: "リアルタイム", hot: "人気", latest: "新着", graduating: "卒業間近", graduated: "卒業済み",
    buy: "購入", sell: "売却", buyWith: "BNBで購入", sellToken: "トークンを売却",
    expectedGet: "受取予定", expectedReceive: "受取予定", fee: "取引手数料",
    switchNetwork: "BNBメインネットへ切替", firstApproveSell: "初回承認して売却",
    approving: "承認確認中…", selling: "売却確認中…", balance: "残高",
    progress: "卒業進捗", target: "目標", loading: "読込中…", internal: "ボンディングカーブ",
    graduatingState: "卒業処理中", graduatedState: "卒業済み", noMatch: "該当プロジェクトはありません",
    risk: "デジタル資産には高いリスクがあります。十分に調査し慎重に取引してください。",
    deploy: "トークン作成", browse: "市場を見る", copied: "コピー済み ✓", copy: "コピー",
    recentTrades: "最近の取引", holders: "ホルダー", topTraders: "アクティブトレーダー", noTopTraders: "識別可能なアクティブトレーダーはいません。", top10Concentration: "上位10アドレス保有比率", noTrades: "まだオンチェーン取引はありません。", noHolders: "ホルダーはいません。",
    readingLogs: "オンチェーンデータを読込中…", items: "件", addresses: "人", theme: "ライト/ダーク切替",
    connectWallet: "ウォレット接続", connectingWallet: "接続中…", openInWallet: "ウォレットで開く",
    createTitle: "トークン設定", tokenName: "トークン名", tokenSymbol: "シンボル", tokenIntro: "説明（任意）",
    tokenLogo: "トークンロゴ（任意）", socialLinks: "コミュニティリンク（任意）", graduationTarget: "卒業目標",
    creatorBuy: "作成者の初回購入（任意）", createToken: "トークン作成",
    curveTrading: "ボンディングカーブ", preparing: "卒業準備", pancake: "PancakeSwap V2",
    myBalance: "残高", supply: "固定総供給量", factoryPermission: "Factory権限",
    graduationPermission: "卒業権限", pairStatus: "Pair送金状態", abandoned: "放棄済み",
    destroyed: "バーン済み", curveOnly: "自動カーブのみ", protected: "卒業前保護", unlocked: "卒業後開放",
    confirmed: "取引が確認されました。", txHash: "取引ハッシュ",
    searchPlaceholder: "トークン名・シンボル・アドレスを検索",
    qqGroupNumber: "QQグループ", qqGroupCopied: "QQグループ情報をコピーしました。QQで検索して参加してください。",
    websitePlaceholder: "公式ウェブサイトを入力 / 任意",
    telegramPlaceholder: "Telegramコミュニティを入力 / 任意",
    twitterPlaceholder: "X（Twitter）リンクを入力 / 任意",
    deboxPlaceholder: "DeBoxコミュニティを入力 / 任意",
    qqPlaceholder: "コミュニティのQQグループを入力 / 任意",
    totalProjects: "全プロジェクト", activeProjects: "ボンディングカーブ", nearGraduation: "卒業間近", completedProjects: "卒業済み",
    chainBusy: "チェーンノードが混雑しています。予備RPCへ自動切替中です…", holderSyncBusy: "ホルダーデータが遅延しているため自動で再試行します。",
    direction: "売買", account: "アカウント", tokenAmount: "トークン", date: "日時", units: "枚",
    chartSyncing: "オンチェーン取引を同期中…", chartEmpty: "取引はまだありません。最初の購入後にローソク足が生成されます。",
    chartBusy: "RPCログが混雑しています。チャートは自動で再試行します。", priceUnit: "価格：BNB / 100万トークン",
    volume: "出来高", liveRefresh: "オンチェーンリアルタイム · 15秒更新", chartTruth: "BNB Chain Mainnet上の実際のボンディングカーブ取引のみを使用し、模擬データは生成しません。",
    templateSelect: "トークンテンプレートを選択", available: "利用可能", unavailable: "利用不可",
    namePlaceholder: "例：BNBX Cat", symbolPlaceholder: "例：BCAT または bcat",
    descriptionPlaceholder: "トークン、コミュニティ、Memeのストーリー（最大500文字）", logoHelp: "JPG、PNG、WebP、GIF対応、最大2MB。",
    initialBuyPlaceholder: "BNB金額を入力", decreaseTarget: "0.01 BNB減らす", increaseTarget: "0.01 BNB増やす",
    factoryMissing: "メインネットFactoryが未設定です。デプロイと検証後に作成機能が有効になります。",
    uploading: "IPFSへアップロード中…", preparingAddress: "末尾1111のコントラクトアドレスを準備中…", walletConfirm: "ウォレットで確認…",
    submitted: "トランザクション送信済み", confirming: "オンチェーン確認中", syncing: "データ同期中", completed: "完了",
    creationSuccess: "BNB Mainnetにトークンを作成しました。", creationFailed: "オンチェーン実行に失敗しました。再送信せず、診断用にトランザクションハッシュを保存してください。",
    safetyTitle: "オンチェーン安全情報", verifiedFactory: "公式Factory", verified: "検証可能", tokenTax: "トークン税", zeroTax: "永久0%", slippage: "価格保護", fixedFee: "カーブ手数料",
    txStatus: "取引状況", walletStep: "ウォレット確認", broadcastStep: "送信済み", confirmStep: "オンチェーン確認", syncStep: "データ更新",
    chooseWallet: "ウォレットを選択", walletConnectHelp: "インストール済みウォレットでBNB Chainへ接続", walletAccount: "マイウォレット",
    copyAddress: "ウォレットアドレスをコピー", viewExplorer: "BscScanで表示", disconnectWallet: "接続解除",
    installed: "インストール済み", install: "インストール / 開く", close: "閉じる", walletSafety: "BNBXがリカバリーフレーズや秘密鍵を求めることはありません。",
    chooseNetwork: "ブロックチェーンを選択", currentNetwork: "現在のネットワーク", comingSoon: "近日対応",
    networkRoadmap: "BNBXマルチチェーン構想", networkSoonHelp: "現在はBNB Chainのみ利用可能です。他のチェーンはコントラクト配備と安全確認後に対応します。",
    raisedBnb: "現在の調達額", remainingBnb: "卒業まで残り", curveRemaining: "カーブ残りトークン",
    automaticMigration: "100%到達後PancakeSwap V2へ自動移行し、LPは永久バーンされます。",
    token: "トークン", creator: "作成者", creatorProjects: "作成者のプロジェクト履歴", launchTime: "作成日", currentPrice: "現在価格", change24h: "24時間変動", liquidity: "流動性", marketCap: "推定時価総額",
    onchainVolume: "オンチェーン出来高", volume24h: "24時間出来高", trades24h: "24時間取引", marketData: "市場データ", officialSite: "公式サイト",
    tokenDescription: "トークン紹介", noTokenDescription: "作成者はトークン紹介を入力していません。",
    expandDescription: "全文を表示", collapseDescription: "閉じる", securityDetails: "安全情報をすべて表示",
    hideSecurityDetails: "安全情報を閉じる", mobileMenu: "メニューを開く", language: "言語",
    moreLinks: "その他", hideLinks: "閉じる", retry: "再読み込み",
    dataUnknown: "確認待ち", dataUnavailable: "オンチェーンデータを一時的に取得できません",
    dataUnavailableHelp: "取得失敗を0として表示しません。しばらくして再試行し、取引前にBscScanで確認してください。",
    partialDataNotice: "一部の項目が遅延中です。不明な値は偽の0ではなく「—」で表示します。",
    staleDataNotice: "リアルタイム更新に一時失敗したため、最後に取得できたデータを表示しています。",
    noProjectsYet: "公開済みプロジェクトはまだありません", noProjectsHelp: "Factoryの読込は成功しましたが、表示できるトークンがありません。",
    metadataUnavailable: "トークン情報を一時的に取得できません。作成者が未入力という意味ではありません。",
    transactionPreview: "ウォレット取引プレビュー", destination: "接続コントラクト",
    creationFee: "作成手数料", initialBuyValue: "作成者の初回購入", totalSend: "ウォレット送信総額",
    minimumReceive: "最低受取量", slippageProtected: "1%最低受取保護",
    tradeLine: "約定ライン", lastUpdated: "更新",
    securityCenter: "安全性・コントラクト", discussion: "プロジェクト討論", signatureNoGas: "ウォレット署名 · Gas不要", commentPlaceholder: "プロジェクトの見解や更新を共有（最大280文字）", connectToComment: "ウォレット接続後に参加できます", postComment: "署名して投稿", noComments: "まだコメントはありません。", commentsUnavailable: "コメントサービスは一時的に利用できません。", commentFailed: "コメントを投稿できませんでした。",
  },
};

const LanguageContext = createContext({
  language: "zh" as Language,
  setLanguage: (language: Language) => { void language; },
  theme: "dark" as Theme,
  toggleTheme: () => {},
  t: (key: string) => messages.zh[key] ?? key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("zh");
  const [theme, setTheme] = useState<Theme>("dark");
  useEffect(() => {
    const saved = localStorage.getItem("bnbx-language") as Language | null;
    if (saved && messages[saved]) setLanguage(saved);
    const savedTheme = localStorage.getItem("bnbx-theme") as Theme | null;
    if (savedTheme === "light" || savedTheme === "dark") setTheme(savedTheme);
  }, []);
  useEffect(() => {
    localStorage.setItem("bnbx-language", language);
    document.documentElement.lang = language === "zh" ? "zh-CN" : language;
  }, [language]);
  useEffect(() => {
    localStorage.setItem("bnbx-theme", theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);
  const value = useMemo(
    () => ({
      language,
      setLanguage,
      theme,
      toggleTheme: () => setTheme((current) => current === "dark" ? "light" : "dark"),
      t: (key: string) => messages[language][key] ?? messages.zh[key] ?? key,
    }),
    [language, theme],
  );
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
